### ISSUE TITLE
unable to retrieve the complete list of server APIs: tenancy.kiosk.sh/v1alpha1

### ISSUE THREAD

**Issue by didieresteves** [loft-sh/kiosk#127]
hi all,

We are stuck when installing Kiosk on new AKS clusters 1.20.06 with the following error : **unable to retrieve the complete list of server APIs: tenancy.kiosk.sh/v1alpha1: the server is currently unable to handle the request**

The logs are in the Kiosk pod which was installed with Helm. We've got the same error with kubectl api-resources

**Kiosk 0.2.0 version**

Important information : the same helm installation works fine when we are on a older version of kubernetes 1.18.

Any help will be appreciated.

Regards.

**Comment by FabianKramm** [comment]
@didieresteves thanks for creating this issue! Is the kiosk pod up and running? If yes, please make sure you allow communication between the api control plane and the pods on port 8443 and 9443 (these might be blocked in some clusters, for private GKE clusters for example this is the case by default)

**Comment by didieresteves** [comment]
Chart updated and it's good by now.
