### ISSUE TITLE
Question: How to setup in existing cluster - Namespace migration

### ISSUE THREAD

**Issue by Merenon** [loft-sh/kiosk#141]
Hi team,

first of all: this extension is awesome and exactly what I was searching for! Amazing work, including the comprehensive documentation and examples :)

I have a question regarding setting kiosk up in an already existing cluster with several "customer namespaces".
How is it possible to migrate existing namespaces to the kiosk space/account structure?

From the documentation I got that:
* Space ownership can be changed, by changing the ownership annotation on the namespace
* During Space creation (or Space ownership changes) a RoleBinding for the owning Account is created in the corresponding Space namespace. The referenced RBAC ClusterRole can be configured in the account.

But apart from the fact that ownership relation has been changed from annotations to labels(?!), this does not seem to work for namespaces that existed before installing kiosk.

Is there any documentation and/or example on how to make this working?
This might be related to and potentially already is the answer: https://github.com/loft-sh/kiosk/issues/140

Many thanks in advance and keep up the great work!

**Comment by karn09** [comment]
It would be great to be able to do this for any existing namespaces. I figured adding it manually under the CRD for Space would do it, but for some reason this resource doesn't get created even after adding new spaces. This makes me think that the docs are outdated. 

Does the paid version (Loft) support namespace migration for existing clusters?

**Comment by FabianKramm** [comment]
Hey @karn09 ! Sorry for the very late response, we had focused more on our other projects. Regarding your question: changing ownership currently does not retrigger the creation part, which is definitely a limitation currently in kiosk.

In our commercial solution (Loft) it is possible to import namespaces (with v3 onwards) and assign templates and objects that should get deployed automatically.

**Comment by Merenon** [comment]
As it is not relevant for us anymore, I'm closing this issue. Feel free to open a new one.
