### ISSUE TITLE
Kiosk: Documentation for predefined parameters

### ISSUE THREAD

**Issue by djmcgreal-cc** [loft-sh/kiosk#153]
I believe [the predefined parameters](https://github.com/loft-sh/kiosk/blob/0a94288f6a1b2a18a4a206c9846714926a07ccde/pkg/manager/controllers/templateinstance_controller.go#L200) are undocumented, but very useful :)

**Comment by alexandradragodan** [comment]
Hey, @djmcgreal-cc 👋 
Thanks for reporting this. Indeed it might have slipped us when documenting. 
Added it on our backlog, yet it might take us a while until we get to it.  Feel free to contribute a PR if you want to and find the time before we get to it. 🚀
