### ISSUE TITLE
About network isolation

### ISSUE THREAD

**Issue by namnx228** [loft-sh/kiosk#45]
Hi,
I wonder if there are any mechanism to isolate network traffic between different tenants in this project ?
I see that you apply network policy in template-manifest, but this policy seems to be applied only in "default" namespace, not for all other namespaces.
Thank you.

**Comment by FabianKramm** [comment]
@namnx228 thanks for opening this issue! I'm not exactly sure what you mean, templates in kiosk define namespace independent resources like network policies, which are then instantiated through a TemplateInstance in the target namespace. So for each namespace you would need a tempalteinstance that references a template that defines a network policy, this process can be automated by defining `account.spec.space.templateInstances` so kiosk will make sure that for each created namespace a template instance with the given template is created.

**Comment by namnx228** [comment]
Ok I see, so there are templates which are cluster-scoped objects, then for each namespace we need to create a TemplateInstance that refers to the global template, so any resources defined in the global templates (like network policy) will also appear in each namespace. So each namespace will have their own network policy. Do I understand right ?

**Comment by FabianKramm** [comment]
@namnx228 yes thats the idea!

**Comment by prames2s** [comment]
@namnx228  I am going through your sidecar manifest, but the sidecar is not able to start with the image. It gives crashloopbackoff error

**Comment by namnx228** [comment]
@prames2s What sidecar manifest are you talking about?

**Comment by prames2s** [comment]
@namnx228  In your repo https://github.com/namnx228/MasterThesis

I am trying to implement the global network policy like you have mentioned, but that blocks the pod communication within the same namespace.
Then I tried the sidecar container, with the python script and json file like below. But the sidecar is not starting. And can you please tell me how did you create the webhook server deployment image.

.py file

#! /usr/bin/env python3
import os
import sys
os.environ["XTABLES_LIBDIR"] = "/usr/lib/x86_64-linux-gnu/xtables"
import iptc
import json
# from sys import stdout

# Input: file name of list IP range
# IPTable manipulate

def add_rule(IP):
    rule=iptc.Rule()
    # Target
    target_ACCEPT = rule.create_target("ACCEPT")
    target_DROP = rule.create_target("DROP")
    
    # Chain
    chain_input=iptc.Chain(iptc.Table(iptc.Table.FILTER), "INPUT")
    chain_output=iptc.Chain(iptc.Table(iptc.Table.FILTER), "OUTPUT")
    
    rule = iptc.Rule()
    rule.src = IP
    rule.dst = IP
    rule.target = target_ACCEPT
    chain_input.insert_rule(rule)
    chain_output.insert_rule(rule)
    

def flush_all():
    chain_input=iptc.Chain(iptc.Table(iptc.Table.FILTER), "INPUT")
    chain_output=iptc.Chain(iptc.Table(iptc.Table.FILTER), "OUTPUT")
    chain_input.flush()
    chain_output.flush()


def Input(filename):
    with open("test.json", 'r') as f:
        ip_range_list = json.load(f)
        return ip_range_list

if len(sys.argv) > 1:
    filename=sys.argv[1]
else:
    filename="test.json"

ip_range_list = Input("test.json")

flush_all()

for item in ip_range_list.items():
    IP = item[1]
    add_rule(IP)


--------------------
.json file

{
    "alice": "172.17.0.0/28",
    "bob": "172.17.1.0/28"
}

**Comment by namnx228** [comment]
@prames2s This is not relevant to loft-sh project, so please discuss it by sending an email to my email address. It is namnx228@gmail.com. I will close this issue.
