### ISSUE TITLE
Debug Mode to see failed rendered chart? 

### ISSUE THREAD

**Issue by dtardoin** [loft-sh/kiosk#99]
I have a TemplateInstance that's failing  a cryptic Helm-related error and I was wondering if there's a way to turn on debug mode for the helm template command so I can see where the chart failed to render?

**Comment by FabianKramm** [comment]
@dtardoin thanks for opening this issue! You can enable the debug mode by setting an environment variable "DEBUG" to true (you can use the chart values `--set-string env.DEBUG=true` for that). However, when a TemplateInstance fails to render there should be a kiosk log entry even without the DEBUG mode enabled, which basically prints what helm gives us back as error message.

Which error message do you receive from helm?

**Comment by dtardoin** [comment]
I think I figured this out, just an issue with my input values formatting. I think this might be a scenario where Helm didn't get to the point where it _would_ have rendered the chart. 

Does debug mode in kiosk actually pass `--debug` on to Helm though?

**Comment by FabianKramm** [comment]
@dtardoin great! No currently we don't pass `--debug` to helm, but if the `DEBUG` environment variable is set, we can do that.
